wandb_version: 1

general:
  desc: null
  value:
    name: graph-tf-model
    wandb: online
    gpus: 1
    resume: null
    test_only: null
    fine_tune: true
    check_val_every_n_epochs: 10
    sample_every_val: 10
    val_check_interval: null
    samples_to_generate: 5
    samples_to_save: 5
    chains_to_save: 1
    log_every_steps: 50
    number_chain_steps: 10
    final_model_samples_to_generate: 20
    final_model_samples_to_save: 2
    final_model_chains_to_save: 2
    evaluate_all_checkpoints: false
model:
  desc: null
  value:
    type: discrete
    transition: marginal
    model: graph_tf
    diffusion_steps: 200
    diffusion_noise_schedule: cosine
    n_layers: 3
    extra_features: null
    hidden_mlp_dims:
      X: 64
      r: 64
      E: 64
      y: 64
    hidden_dims:
      dx: 128
      dr: 128
      de: 128
      dy: 64
      n_head: 16
      dim_ffX: 256
      dim_ffE: 128
      dim_ffy: 128
    lambda_train:
    - 0
    - 0
train:
  desc: null
  value:
    n_epochs: 200
    batch_size: 1
    lr: 0.001
    clip_grad: null
    save_model: true
    num_workers: 0
    ema_decay: 0
    progress_bar: true
    weight_decay: 1.0e-12
    optimizer: adamw
    seed: 0
dataset:
  desc: null
  value:
    name: schenker
    remove_h: null
    datadir: data/schenker/processed/heterdatacleaned/
_wandb:
  desc: null
  value:
    python_version: 3.10.16
    cli_version: 0.15.4
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1746736746.901604
    t:
      1:
      - 1
      - 9
      - 41
      - 50
      - 55
      - 77
      2:
      - 1
      - 9
      - 41
      - 50
      - 55
      - 77
      3:
      - 3
      - 13
      - 16
      - 23
      4: 3.10.16
      5: 0.15.4
      8:
      - 5
